server:
    port: 8080
    contextPath: /GishoMS
        
security:
    oauth2:
        resource:
            jwt:
                # Tells the JWT framework to fetch the public key from the authorization server during startup
                # Note: The authorization server needs to be running...
                key-uri: "http://localhost:8081/GishoMSAuthService/oauth/token_key"
                


spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/Gisho
        name:
        username: postgres
        password: super
        
    profiles.active: dev
    

